version: "3.8"
services:
  
  ngix:
    networks:
      - inception
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - wordpress

  mariadb:
    networks:
      - inception
    build:  ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
  
  wordpress:
    networks:
      - inception
    build:  ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/mkorchi/data/mariadb
      type: none
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/mkorchi/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

