version: "3.8"
services:
  
  ngix:
    networks:
      - inception
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - wordpress

  mariadb:
    networks:
      - inception
    build:  ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
  
  wordpress:
    networks:
      - inception
    build:  ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always

  website:
    networks:
      - inception
    build: ./requirements/bonus/website
    container_name: website
    image: website
    ports:
      - 9991:9991
    restart: always

  redis:
    networks:
      - inception
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    restart: always
  

  adminer:
    networks:
      - inception
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - 5055:5055
    restart: always

  cadvisor:
    image: cadvisor
    build: ./requirements/bonus/cadvisor/
    container_name: cadvisor
    networks:
      - inception
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/mkorchi/data/mariadb
      type: none
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/mkorchi/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception

